Repository tscircuit/docs, pull requests merged in 2025-09, with the labels that each got.

#127 docs: add expressions guide
  docs/guides/using-expressions.mdx
Labels: codex

#132 fix: properly fix the empty white space
  src/components/CircuitPreview.tsx
Labels: 💰 Rewarded

#137 Fix: Sidebar Issue by introducing `hideableSidebar`
  docusaurus.config.ts
Labels: 🙋 Bounty claim

#146 docs: add kicad footprint tip
  docs/elements/chip.mdx
  docs/guides/importing-modules-and-chips/importing-from-kicad.md
Labels: codex

#147 docs: document testpoint layer property
  docs/elements/testpoint.mdx
Labels: codex

#148 Add example usage of polygon <smtpad />
  docs/footprints/smtpad.mdx
Labels: 🙋 Bounty claim

#149 docs: expand contribution sponsorship details
  docs/contributing/bounties-and-sponsorship.md
Labels: codex

#154 Fixed the code block scroll bar
  src/css/custom.css
Labels: 🙋 Bounty claim

#155 Add documentation for fabricationnotetext element
  docs/elements/fabricationnotetext.mdx
Labels: codex

#156 Move fabricationnotetext doc to footprints
  docs/footprints/fabricationnotetext.mdx
Labels: codex

#157 docs: document board origin offset props
  docs/elements/board.mdx
Labels: codex
